### ISSUE TITLE
Running napari fails with napari-aydin installed

### ISSUE THREAD

**Issue by haesleinhuepf** [royerlab/napari-aydin#5]
Hi @AhmetCanSolak ,

I just tried to run the plugin from [this branch](https://github.com/royerlab/napari-aydin/tree/functional-plugin-implementation). 

I set up a new conda environment and only installed `pip install -e .` The installation worked ok, but when starting napari, I receive this error: `DLL load failed while importing shell: The specified procedure could not be found.` Not sure which DLL it is trying to load.

Any hint is appreciated!

Here are more details:

```
(aydin) C:\structure\code\napari-aydin>napari
Traceback (most recent call last):
  File "C:\Users\rober\miniconda3\envs\aydin\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rober\miniconda3\envs\aydin\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\rober\miniconda3\envs\aydin\Scripts\napari.exe\__main__.py", line 7, in <module>
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\__main__.py", line 431, in main
    _run()
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\__main__.py", line 230, in _run
    from napari import run, view_path
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\_lazy.py", line 47, in __getattr__
    submod = import_module(f'{module_name}.{attr_to_modules[name]}')
  File "C:\Users\rober\miniconda3\envs\aydin\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\view_layers.py", line 17, in <module>
    from .viewer import Viewer
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\viewer.py", line 5, in <module>
    from .components.viewer_model import ViewerModel
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\components\__init__.py", line 17, in <module>
    from .camera import Camera
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\components\camera.py", line 6, in <module>
    from ..utils.events import EventedModel
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\utils\__init__.py", line 2, in <module>
    from .colormaps import Colormap
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\utils\colormaps\__init__.py", line 2, in <module>
    from .colormap import Colormap
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\utils\colormaps\colormap.py", line 7, in <module>
    from ..events import EventedModel
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\utils\events\__init__.py", line 1, in <module>
    from .event import EmitterGroup, Event, EventEmitter  # isort:skip
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\utils\events\event.py", line 71, in <module>
    from ..translations import trans
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\utils\translations.py", line 14, in <module>
    from ._base import _DEFAULT_CONFIG_PATH, _DEFAULT_LOCALE
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\utils\_base.py", line 14, in <module>
    _DEFAULT_CONFIG_PATH = user_config_dir(_APPNAME, _APPAUTHOR, _FILENAME)
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\appdirs.py", line 196, in user_config_dir
    path = user_data_dir(appname, appauthor, None, roaming)
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\appdirs.py", line 81, in user_data_dir
    path = os.path.normpath(_get_win_folder(const))
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\appdirs.py", line 480, in _get_win_folder_with_pywin32
    from win32com.shell import shellcon, shell
ImportError: DLL load failed while importing shell: The specified procedure could not be found.

(aydin) C:\structure\code\napari-aydin>napari
Traceback (most recent call last):
  File "C:\Users\rober\miniconda3\envs\aydin\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rober\miniconda3\envs\aydin\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\rober\miniconda3\envs\aydin\Scripts\napari.exe\__main__.py", line 7, in <module>
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\__main__.py", line 431, in main
    _run()
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\__main__.py", line 230, in _run
    from napari import run, view_path
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\_lazy.py", line 47, in __getattr__
    submod = import_module(f'{module_name}.{attr_to_modules[name]}')
  File "C:\Users\rober\miniconda3\envs\aydin\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\view_layers.py", line 17, in <module>
    from .viewer import Viewer
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\viewer.py", line 5, in <module>
    from .components.viewer_model import ViewerModel
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\components\__init__.py", line 17, in <module>
    from .camera import Camera
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\components\camera.py", line 6, in <module>
    from ..utils.events import EventedModel
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\utils\__init__.py", line 2, in <module>
    from .colormaps import Colormap
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\utils\colormaps\__init__.py", line 2, in <module>
    from .colormap import Colormap
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\utils\colormaps\colormap.py", line 7, in <module>
    from ..events import EventedModel
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\utils\events\__init__.py", line 1, in <module>
    from .event import EmitterGroup, Event, EventEmitter  # isort:skip
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\utils\events\event.py", line 71, in <module>
    from ..translations import trans
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\utils\translations.py", line 14, in <module>
    from ._base import _DEFAULT_CONFIG_PATH, _DEFAULT_LOCALE
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\napari\utils\_base.py", line 14, in <module>
    _DEFAULT_CONFIG_PATH = user_config_dir(_APPNAME, _APPAUTHOR, _FILENAME)
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\appdirs.py", line 196, in user_config_dir
    path = user_data_dir(appname, appauthor, None, roaming)
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\appdirs.py", line 81, in user_data_dir
    path = os.path.normpath(_get_win_folder(const))
  File "C:\Users\rober\miniconda3\envs\aydin\lib\site-packages\appdirs.py", line 480, in _get_win_folder_with_pywin32
    from win32com.shell import shellcon, shell
ImportError: DLL load failed while importing shell: The specified procedure could not be found.

(aydin) C:\structure\code\napari-aydin>
```

That's my `conda list`:

```
# packages in environment at C:\Users\rober\miniconda3\envs\aydin:
#
# Name                    Version                   Build  Channel
absl-py                   1.1.0                    pypi_0    pypi
alabaster                 0.7.12                   pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
asttokens                 2.0.5                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
aydin                     0.1.14                   pypi_0    pypi
babel                     2.10.3                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
ca-certificates           2022.4.26            haa95532_0
cachetools                5.2.0                    pypi_0    pypi
cachey                    0.2.1                    pypi_0    pypi
catboost                  1.0.5                    pypi_0    pypi
certifi                   2022.6.15        py39haa95532_0
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.0.3                    pypi_0    pypi
cloudpickle               2.1.0                    pypi_0    pypi
colorama                  0.4.5                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
czifile                   2019.7.2                 pypi_0    pypi
dask                      2022.6.1                 pypi_0    pypi
debugpy                   1.6.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
docstring-parser          0.13                     pypi_0    pypi
docutils                  0.18.1                   pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 0.8.3                    pypi_0    pypi
fasteners                 0.17.3                   pypi_0    pypi
filelock                  3.7.1                    pypi_0    pypi
flatbuffers               2.0                      pypi_0    pypi
fonttools                 4.33.3                   pypi_0    pypi
freetype-py               2.3.0                    pypi_0    pypi
fsspec                    2022.5.0                 pypi_0    pypi
gast                      0.5.3                    pypi_0    pypi
gdown                     4.2.0                    pypi_0    pypi
git                       2.34.1               haa95532_0
google-auth               2.8.0                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
googledrivedownloader     0.4                      pypi_0    pypi
grpcio                    1.47.0                   pypi_0    pypi
h5py                      3.7.0                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
hsluv                     5.0.3                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
imagecodecs               2022.2.22                pypi_0    pypi
imageio                   2.19.3                   pypi_0    pypi
imagesize                 1.3.0                    pypi_0    pypi
importlib-metadata        4.10.0                   pypi_0    pypi
ipykernel                 6.15.0                   pypi_0    pypi
ipython                   8.4.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jsonpickle                1.3                      pypi_0    pypi
jsonschema                4.6.0                    pypi_0    pypi
jupyter-client            7.3.4                    pypi_0    pypi
jupyter-core              4.10.0                   pypi_0    pypi
keras                     2.8.0                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.4.3                    pypi_0    pypi
libclang                  14.0.1                   pypi_0    pypi
lightgbm                  3.3.1                    pypi_0    pypi
llvmlite                  0.38.1                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
magicgui                  0.5.1                    pypi_0    pypi
markdown                  3.3.7                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.2                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
memoization               0.4.0                    pypi_0    pypi
napari                    0.4.12                   pypi_0    pypi
napari-aydin              0.1.dev5+gc66e472.d20220626           dev_0    <develop>
napari-console            0.0.4                    pypi_0    pypi
napari-plugin-engine      0.2.0                    pypi_0    pypi
napari-svg                0.1.6                    pypi_0    pypi
nd2reader                 3.3.0                    pypi_0    pypi
nest-asyncio              1.5.5                    pypi_0    pypi
networkx                  2.8.4                    pypi_0    pypi
numba                     0.55.1                   pypi_0    pypi
numcodecs                 0.10.0                   pypi_0    pypi
numexpr                   2.8.1                    pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
numpydoc                  1.4.0                    pypi_0    pypi
oauthlib                  3.2.0                    pypi_0    pypi
openssl                   1.1.1o               h2bbff1b_0
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.4.3                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
partd                     1.2.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.1.1                    pypi_0    pypi
pims                      0.6.1                    pypi_0    pypi
pint                      0.19.2                   pypi_0    pypi
pip                       21.2.4           py39haa95532_0
plotly                    5.9.0                    pypi_0    pypi
prompt-toolkit            3.0.29                   pypi_0    pypi
protobuf                  3.20.1                   pypi_0    pypi
psutil                    5.9.1                    pypi_0    pypi
psygnal                   0.3.5                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pydantic                  1.9.1                    pypi_0    pypi
pygments                  2.12.0                   pypi_0    pypi
pynndescent               0.5.5                    pypi_0    pypi
pyopengl                  3.1.6                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyqt5                     5.15.6                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.11.0                  pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
python                    3.9.12               h6244533_0
python-dateutil           2.8.2                    pypi_0    pypi
python-graphviz           0.20                     pypi_0    pypi
pytz                      2022.1                   pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pywin32                   304                      pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     23.2.0                   pypi_0    pypi
qdarkstyle                3.0.2                    pypi_0    pypi
qtconsole                 5.2.2                    pypi_0    pypi
qtpy                      1.11.2                   pypi_0    pypi
requests                  2.28.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
scikit-image              0.18.3                   pypi_0    pypi
scikit-learn              1.1.1                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
setuptools                61.2.0           py39haa95532_0
six                       1.16.0                   pypi_0    pypi
slicerator                1.1.0                    pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sphinx                    5.0.2                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.38.5               h2bbff1b_0
stack-data                0.3.0                    pypi_0    pypi
superqt                   0.3.2                    pypi_0    pypi
tenacity                  8.0.1                    pypi_0    pypi
tensorboard               2.8.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.8.1                    pypi_0    pypi
tensorflow-estimator      2.8.0                    pypi_0    pypi
tensorflow-io-gcs-filesystem 0.26.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2022.5.4                 pypi_0    pypi
toolz                     0.11.2                   pypi_0    pypi
torch                     1.10.1                   pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.64.0                   pypi_0    pypi
traitlets                 5.3.0                    pypi_0    pypi
typing-extensions         4.2.0                    pypi_0    pypi
tzdata                    2022a                hda174b7_0
urllib3                   1.26.9                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vispy                     0.10.0                   pypi_0    pypi
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5                    pypi_0    pypi
werkzeug                  2.1.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py39haa95532_2
wrapt                     1.14.1                   pypi_0    pypi
xmltodict                 0.13.0                   pypi_0    pypi
zarr                      2.4.0                    pypi_0    pypi
zipp                      3.8.0                    pypi_0    pypi
```

**Comment by haesleinhuepf** [comment]
Related issue:
* https://github.com/napari/napari/issues/3634

(But the solution discussed there does not work)

**Comment by haesleinhuepf** [comment]
The issue can apparently be resolved by 

```
pip uninstall napari
conda install napari==0.4.15 -c conda-forge
```

Obviously, this installs a newer version of napari though...

**Comment by AhmetCanSolak** [comment]
> The issue can apparently be resolved by
> 
> ```
> pip uninstall napari
> conda install napari==0.4.15 -c conda-forge
> ```
> 
> Obviously, this installs a newer version of napari though...

Are you okay with pinning napari to 0.4.15 for now @haesleinhuepf ? I think it is okay on my end.

**Comment by AhmetCanSolak** [comment]
btw, I couldn't reproduce the same problem with same branch on Windows 10 with Anaconda 4.10.3 @haesleinhuepf . fyi

**Comment by haesleinhuepf** [comment]
I presume it has something to do with coexistence of older and new napari versions in different conda environments on my system... 

> Are you okay with pinning napari to 0.4.15 for now @haesleinhuepf ? I think it is okay on my end.

Yes! I also just relaxed the napari dependency in [devbio-napari](https://github.com/haesleinhuepf/devbio-napari/releases) to make it compatible with napari-aydin.

I'm closing this as it's indeed hard to reproduce. Thanks for the feedback!
